version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - "3306:3306"

  hospital-service:
    build: .
    image: hyidi/hospital-service
    container_name: hospital-service
    env_file:
      - ./.env
    depends_on:
      - mysql
    ports:
      - "8088:8088"